"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var OpenArraySorter_1 = require("./OpenArraySorter");
var sorter = new OpenArraySorter_1.OpenArraySorter([1, 2, 3, 4, 5, 6, 7]);
sorter.shuffle();
console.log(sorter.data);
var copy = sorter.data;
sorter.alphabetize();
console.log(sorter.data);
console.log(copy);
